// Cross-platform "launch the daemon at user login" installer.
// Goal: after `claudex init`, the bridge survives reboots without the user
// touching anything. No admin/sudo. Cleanly uninstallable.

import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir, platform } from "node:os";
import { join } from "node:path";

export interface AutostartResult {
  ok: boolean;
  path: string;
  reason?: string;
}

export function installAutostart(daemonScriptPath: string): AutostartResult {
  switch (platform()) {
    case "win32":
      return installAutostartWindows(daemonScriptPath);
    case "darwin":
      return installAutostartMac(daemonScriptPath);
    default:
      return installAutostartLinux(daemonScriptPath);
  }
}

export function uninstallAutostart(): AutostartResult {
  switch (platform()) {
    case "win32":
      return removeIfExists(windowsAutostartPath());
    case "darwin":
      return removeIfExists(macAutostartPath());
    default:
      return removeIfExists(linuxAutostartPath());
  }
}

// ---------------- Windows ----------------

function windowsStartupDir(): string {
  return join(
    homedir(),
    "AppData",
    "Roaming",
    "Microsoft",
    "Windows",
    "Start Menu",
    "Programs",
    "Startup",
  );
}

function windowsAutostartPath(): string {
  return join(windowsStartupDir(), "claudex.vbs");
}

function installAutostartWindows(daemonScriptPath: string): AutostartResult {
  const dir = windowsStartupDir();
  if (!existsSync(dir)) {
    return { ok: false, path: dir, reason: "Startup folder not found" };
  }
  const vbsPath = windowsAutostartPath();
  const nodePath = process.execPath;
  // 0 = hidden window, False = don't wait. Quoting both args so paths with spaces work.
  const vbs =
    `' Auto-generated by claudex (https://github.com/unlikesooraj/claudex)\r\n` +
    `' Launches the claudex daemon at user login, no window.\r\n` +
    `CreateObject("Wscript.Shell").Run """${nodePath}"" ""${daemonScriptPath}""", 0, False\r\n`;
  writeFileSync(vbsPath, vbs, "utf8");
  return { ok: true, path: vbsPath };
}

// ---------------- macOS ----------------

function macAutostartPath(): string {
  return join(homedir(), "Library", "LaunchAgents", "com.claudex.daemon.plist");
}

function installAutostartMac(daemonScriptPath: string): AutostartResult {
  const path = macAutostartPath();
  const dir = join(homedir(), "Library", "LaunchAgents");
  if (!existsSync(dir)) {
    try {
      mkdirSync(dir, { recursive: true });
    } catch (e) {
      return { ok: false, path, reason: `mkdir failed: ${e}` };
    }
  }
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.claudex.daemon</string>
  <key>ProgramArguments</key>
  <array>
    <string>${process.execPath}</string>
    <string>${daemonScriptPath}</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${join(homedir(), ".claudex", "daemon.log")}</string>
  <key>StandardErrorPath</key><string>${join(homedir(), ".claudex", "daemon.log")}</string>
</dict>
</plist>
`;
  writeFileSync(path, plist, "utf8");
  return {
    ok: true,
    path,
    reason: `Run \`launchctl load ${path}\` to start now, or just log out and back in.`,
  };
}

// ---------------- Linux ----------------

function linuxAutostartPath(): string {
  return join(homedir(), ".config", "systemd", "user", "claudex.service");
}

function installAutostartLinux(daemonScriptPath: string): AutostartResult {
  const path = linuxAutostartPath();
  const dir = join(homedir(), ".config", "systemd", "user");
  try {
    mkdirSync(dir, { recursive: true });
  } catch (e) {
    return { ok: false, path, reason: `mkdir failed: ${e}` };
  }
  const unit = `[Unit]
Description=claudex daemon (Claude Code <-> Codex CLI session bridge)
After=default.target

[Service]
ExecStart=${process.execPath} ${daemonScriptPath}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
`;
  writeFileSync(path, unit, "utf8");
  return {
    ok: true,
    path,
    reason: `Run \`systemctl --user enable --now claudex.service\` to start now.`,
  };
}

// ---------------- shared ----------------

function removeIfExists(path: string): AutostartResult {
  if (!existsSync(path)) return { ok: true, path, reason: "not installed" };
  try {
    unlinkSync(path);
    return { ok: true, path };
  } catch (e) {
    return { ok: false, path, reason: `unlink failed: ${e}` };
  }
}
